config/routes.rb
Rails.application.routes.draw do
  resources :rsvps
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "web#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  validate :rsvps_can_only_be_wed_thu, on: [:create, :update]
  validates :pax, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validates :telephone, presence: true, length: {in: 9..15}

  # def rsvp_date
  #   self[:rsvp_date].strftime("%d/%m/%Y")
  # end

private

  def rsvps_can_only_be_wed_thu #rsvps only admited for Tuesdays and Wednesdays
    if !(self.rsvp_date.strftime("%a") == "Thu" || self.rsvp_date.strftime("%a") == "Wed")
      self.errors.add(:rsvp_date, "Sólo se admiten reservas Miércoles y Jueves")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :check_permissions, except: [:new, :create]
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]


  def index
    @active = params[:active] == "true" ? true : false
    if @active == true
      @rsvps = Rsvp.where("rsvp_date >= ?", Date.today).order(:rsvp_date, :rsvp_time)
    else
      @rsvps = Rsvp.all
    end
  end

  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if helpers.free_spots(@rsvp.rsvp_date) >= @rsvp.pax
      respond_to do |format|
        if @rsvp.save
          format.html { redirect_to root_path}
        else
          format.html { render action: :new }
        end
      end
    else
      @rsvp.errors.add :name, "No quedan plazas disponibles para ese día. Lamentamos las molestias."
      render action: :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        flash[:notice] =  'La reserva se ha actualizado.'
        format.html { redirect_to action: :index }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @rsvp.destroy
    respond_to do |format|
      flash[:notice] =  'La reserva se ha eliminado.'
      format.html { redirect_to action: :index }
    end
  end

private
  def set_rsvp
    @rsvp = Rsvp.find(params[:id])
  end

  def check_permissions
    unless user_signed_in?
      redirect_to root_path
    end

  end

  def rsvp_params
    params.require(:rsvp).permit(:name, :rsvp_date, :pax, :telephone, :rsvp_time, "g-recaptcha-response")
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController

  def index
  end


private


  def check_permissions
    unless user_signed_in?
      redirect_to root_path
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  def can_edit_phrases?
   user_signed_in? #only editors can sign in, so anyone signed in is a verified editor.
  end
end

app/helpers/rsvp_helper.rb
module RsvpHelper

  def free_spots(date)
    40 - Rsvp.where("rsvp_date = ?", date.strftime("%Y-%m-%d 00:00:00")).sum(:pax)
  end

  def spots_for_next(weekday = "Wed")
    40 - Rsvp.where("rsvp_date = ?", next_weekday(weekdays.index weekday).strftime("%Y-%m-%d 00:00:00")).sum(:pax)
  end

  # method to return the date of the next weekday to happen using the position of the weekday [Sun, 0] [Mon, 1] [Tue, 2] [Wed, 3], etc.
  def next_weekday(weekday = 2)
    date = Date.today
    unless date.strftime("%w") == weekday.to_s
      date += 1 + ((weekday -1 -date.wday) % 7)
    end
    date
  end

private
  def weekdays
    ["Sun","Mon","Tue","Wed","Thu", "Fri", "Sat"]
  end
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "Restaurante Salón Laurel del IES Felo Monzón", :name => "description"}/
    %meta{:content => "g0ldan", :name => "author"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %title Restaurante Salón Laurel
    / Custom fonts for this template
    %link{:href => "https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i", :rel => "stylesheet"}/
  %body
    = render 'phrasing/initializer'
    -unless notice.nil? || alert.nil?
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/rsvps/_form.html.haml
.row.justify-content-center
  .col-md-4.border.m-3
    = form_for @rsvp do |f|
      - if @rsvp.errors.any?
        #error_explanation
          %h4= "Se han encontrado #{(@rsvp.errors.count)} errores:"
          %ul
            - @rsvp.errors.messages.each do |message|
              %li= message[1][0]

      .form-group
        %label{:for => "nombre"} Nombre
        = f.text_field :name, id: "nombre", class: "form-control", required: true
        %small#nombre.form-text.text-muted Introduzca un nombre para la reserva

      .form-group
        %label{:for => "rsvp_date"} Fecha de Reserva
        =f.text_field :rsvp_date, id: "rsvp_date", class: "form-control", required: true
        %small#rsvp_date_help.form-text.text-muted Introduzca una fecha para la reserva

      .form-group
        %label{:for => "rsvp_time"} Hora de Reserva
        =f.select :rsvp_time, options_for_select(['14:00', '14:15', '14:30', '14:45', '15:00', '15:15', '15:30', '15:45'], selected: @rsvp.rsvp_time.strftime("%H:%M")),{}, {id: "rsvp_time", class: "form-control", required: true}
        %small#rsvp_time.form-text.text-muted Introduzca una hora para la reserva

      .form-group
        %label{:for => "pax"} Pax de la Reserva
        =f.text_field :pax, id: "pax", class: "form-control", required: true, type: "number", value: 1, min: 1, max: 100
        %small#pax.form-text.text-muted Introduzca para cuántas personas es la reserva

      .form-group
        %label{:for => "telephone"} Teléfono de contacto para la Reserva
        =f.text_field :telephone, id: "telephone", class: "form-control", required: true, type: "telephone"
        %small#telephone.form-text.text-muted Introduzca un teléfono de contacto para cualquier consulta relacionada con la reserva




      %br/
      .row.justify-content-center= f.submit 'Reservar', class:"btn-xl btn-primary"

    .row.justify-content-right= link_to 'Cancelar', root_path, class:"btn btn-warning"

app/views/rsvps/edit.html.haml
.row.justify-content-center
  .col-md-4.border.m-3
    %h1 Editar Reserva
= render 'form'

= link_to 'Reservas', rsvps_path, class: "btn btn-primary"

app/views/rsvps/index.html.haml
.row
  .col-md-12
    .h1.text-center
      = link_to 'Nueva Reserva', new_rsvp_path, class: "btn btn-success"
      Reservas activas
      - if @active
        =link_to "Ver todas", rsvps_path(active:false), class: "btn btn-primary"
      - else
        =link_to "Ver activas", rsvps_path(active:true), class: "btn btn-primary"
.row.small
  .col.h5.text-center
    ="Martes #{next_weekday.strftime("%d/%m")}"
    %br/
    =" #{spots_for_next("Tue")} plazas libres"
  .col.h5.text-center
    ="Miércoles #{next_weekday.strftime("%d/%m")}"
    %br/
    =" #{spots_for_next("Wed")} plazas libres"
.row
  .col.text-center
    .table-responsive
      %table.table.table-bordered.text-center
        %thead
          %tr{scope: "row"}
            %th{scope: "col"} Nombre
            %th{scope: "col"} Pax
            %th{scope: "col"} Día y Hora
            %th{scope: "col"} Teléfono
            %th{scope: "col", colspan: 2}

        %tbody
          - @rsvps.each do |rsvp|
            %tr{scope: "row"}
              %td{scope: "col"}= rsvp.name
              %td{scope: "col"}= rsvp.pax
              %td{scope: "col"}="#{rsvp.rsvp_date.strftime("%a %d/%m")} #{rsvp.rsvp_time.strftime("%H:%M")}"
              %td{scope: "col"}= rsvp.telephone
              %td{scope: "col"}
                =link_to edit_rsvp_path(rsvp) do
                  =image_tag "svg/pencil.svg", width: "16px"
              %td{scope: "col"}
                = link_to rsvp, method: :delete, data: { confirm: '¿Está seguro de eliminar esta reserva?' } do
                  =image_tag "svg/x.svg", width: "16px"


%br/

app/views/rsvps/new.html.haml
.row.justify-content-center
  .col-md-4.border.m-3
    %h1.text-center Reservar
= render 'form'

app/views/rsvps/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_rsvp_path(@rsvp)
\|
= link_to 'Back', rsvps_path

app/views/web/index.html.haml
/ Navigation
%nav.navbar.navbar-expand-lg.navbar-dark.navbar-custom.fixed-top
  .container
    %a.navbar-brand{:href => "#"} Salón Laurel
    %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          %a.nav-link{:href => "#menu"} Menú de la Semana
        %li.nav-item
          %a.nav-link{:href => "#reservas"} Reservas
        %li.nav-item
          - if user_signed_in?
            %small=link_to "Gestión", rsvps_path, class: "nav-link small"
          - else
            =link_to "Log In", new_user_session_path, class: "nav-link"
%header.masthead.text-center.text-white
  .masthead-content
    .container
      %h1.masthead-heading.mb-0 Salón Laurel
      %h3.mb-0 Instituto Felo Monzón
      / %a.btn.btn-primary.btn-xl.rounded-pill.mt-5{:href => "#"} Learn More
%section#who-are-we
  .container
    .row.align-items-center
      .col-lg-12
        .p-5
          %h4 ¿Quienes somos?
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.
      %hr.col-md-12/
%section#menu
  .container
    .row
      .col-lg-6.col-xs-12
        .p-3.daily-menu
          %h4.text-center="Menú Miércoles #{next_weekday(3).day}"
          .col.h5.text-center
            =" #{spots_for_next("Wed")} plazas libres"
          %hr/
          .font-weight-bold.first.dish Primer plato
          %ul
            %li=phrase("plato_m 1.1")
            %li=phrase("plato_m 1.2")
            %li=phrase("plato_m 1.3")
            %li=phrase("plato_m 1.4")
          .font-weight-bold.second.dish Segundo plato
          %ul
            %li=phrase ("plato_m 2.1")
            %li=phrase ("plato_m 2.2")
            %li=phrase ("plato_m 2.3")
            %li=phrase ("plato_m 2.4")
      .col-lg-6.col-xs-12
        .p-3.daily-menu
          %h4.text-center="Menú Jueves #{next_weekday(4).day}"
          .col.h5.text-center
            =" #{spots_for_next("Thu")} plazas libres"
          %hr/
          .font-weight-bold.first.dish Primer plato
          %ul
            %li=phrase("plato_x 1.1")
            %li=phrase("plato_x 1.2")
            %li=phrase("plato_x 1.3")
            %li=phrase("plato_x 1.4")
          .font-weight-bold.second.dish Segundo plato
          %ul
            %li=phrase ("plato_x 2.1")
            %li=phrase ("plato_x 2.2")
            %li=phrase ("plato_x 2.3")
            %li=phrase ("plato_x 2.4")
    .row.align-items-center
      .col.text-center
        =image_tag "allergens.png", class: "img img-fluid img-thumbnail"
%section#reservas
  .container
    .row.align-items-center
      .col-lg-12.order-lg-1
        .p-5
          %h4 Reservas
          %p
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.
            %br/
          .row.justify-content-center=link_to "Reservar", new_rsvp_path,  class: "btn-xl btn-primary pull-center"
/ Footer
%footer.py-5.bg-black
  .container
    %p.m-0.text-center.text-white.small Copyright &#169; Felo 2019
  / /.container